apiVersion: v1
kind: Service
metadata:
  name: todo-webclient-service
spec:
  selector:
    app: todo
    tier: webclient
  ports:
    - protocol: TCP
      port: 80  # The port on which the service is exposed
      targetPort: 3000  # The port on the container
  type: ClusterIP
