apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-webserver
spec:
  selector:
    matchLabels:
      app: todo-webserver
  template:
    metadata:
      labels:
        app: todo-webserver
    spec:
      containers:
        - name: todo-webserver
          image: swikrititripathi/todo-webserver:v0.3
          env:
            - name: PORT
              value: "8080"
        - name: todo-webclient
          image: swikrititripathi/todo-webclient:v0.3
